env: "prod"

grpc:
  booking:
    port: 60008
  public:
    port: 60009

database:
  host: "postgres-resource-service"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "resource_service"
  ssl_mode: "disable"
